name: deploy-gh-page
on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone public repo via HTTPS
      uses: chihqiang/checkout-action@main
      with:
        repo: ${{ secrets.PRIVATE_REPO }}
        branch: main
        token: ${{ secrets.GH_TOKEN }}
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: hexo build 
      run: cd repo && make build
    - name: Publish to gh-pages branch
      uses: chihqiang/gh-pages-action@main
      with:
        publish_dir: repo/public
        target_branch: gh-pages
        cname: www.zhiqiang.wang
        token: ${{ secrets.GH_TOKEN }}
